# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.body_widget = QtWidgets.QWidget(self.centralwidget)
        self.body_widget.setMinimumSize(QtCore.QSize(1002, 500))
        self.body_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.body_widget.setStyleSheet("")
        self.body_widget.setObjectName("body_widget")
        self.params_widget = QtWidgets.QWidget(self.body_widget)
        self.params_widget.setGeometry(QtCore.QRect(240, 210, 491, 391))
        self.params_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.params_widget.setAutoFillBackground(False)
        self.params_widget.setStyleSheet("background: #003153;\n"
"border-radius:30px;\n"
"color:#fff;\n"
"font-weight: bold;\n"
"margin: 0 auto;")
        self.params_widget.setObjectName("params_widget")
        self.problem_label = QtWidgets.QLabel(self.params_widget)
        self.problem_label.setGeometry(QtCore.QRect(40, 40, 411, 13))
        self.problem_label.setStyleSheet("margin:0 auto;")
        self.problem_label.setScaledContents(False)
        self.problem_label.setAlignment(QtCore.Qt.AlignCenter)
        self.problem_label.setObjectName("problem_label")
        self.problem_input = QtWidgets.QLineEdit(self.params_widget)
        self.problem_input.setGeometry(QtCore.QRect(40, 80, 411, 61))
        self.problem_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.problem_input.setStyleSheet("border:2px solid #fff;\n"
"border-radius:30px;\n"
"color:#fff;\n"
"background:#282828;")
        self.problem_input.setText("")
        self.problem_input.setAlignment(QtCore.Qt.AlignCenter)
        self.problem_input.setObjectName("problem_input")
        self.parse_button = QtWidgets.QPushButton(self.params_widget)
        self.parse_button.setEnabled(True)
        self.parse_button.setGeometry(QtCore.QRect(140, 170, 211, 23))
        self.parse_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.parse_button.setStyleSheet("background:#223DF5;")
        self.parse_button.setDefault(False)
        self.parse_button.setObjectName("parse_button")
        self.status_label = QtWidgets.QLabel(self.params_widget)
        self.status_label.setGeometry(QtCore.QRect(130, 220, 247, 13))
        self.status_label.setObjectName("status_label")
        self.control_label = QtWidgets.QLabel(self.params_widget)
        self.control_label.setGeometry(QtCore.QRect(50, 250, 391, 41))
        self.control_label.setMinimumSize(QtCore.QSize(300, 13))
        self.control_label.setStyleSheet("margin:0 auto;")
        self.control_label.setText("")
        self.control_label.setAlignment(QtCore.Qt.AlignCenter)
        self.control_label.setObjectName("control_label")
        self.show_statistic_button = QtWidgets.QPushButton(self.params_widget)
        self.show_statistic_button.setEnabled(True)
        self.show_statistic_button.setGeometry(QtCore.QRect(140, 340, 211, 23))
        self.show_statistic_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.show_statistic_button.setStyleSheet("background:#223DF5;")
        self.show_statistic_button.setDefault(False)
        self.show_statistic_button.setObjectName("show_statistic_button")
        self.save_results_button = QtWidgets.QPushButton(self.params_widget)
        self.save_results_button.setEnabled(True)
        self.save_results_button.setGeometry(QtCore.QRect(140, 310, 211, 23))
        self.save_results_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_results_button.setStyleSheet("background:#223DF5;")
        self.save_results_button.setDefault(False)
        self.save_results_button.setObjectName("save_results_button")
        self.parser_title = QtWidgets.QLabel(self.body_widget)
        self.parser_title.setEnabled(True)
        self.parser_title.setGeometry(QtCore.QRect(370, 70, 217, 30))
        self.parser_title.setStyleSheet("font-weight: bold;\n"
"font-size: 25px;\n"
"background: none;\n"
"color:#282828;")
        self.parser_title.setObjectName("parser_title")
        self.verticalLayout_3.addWidget(self.body_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.save_result = QtWidgets.QAction(MainWindow)
        self.save_result.setObjectName("save_result")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.problem_label.setText(_translate("MainWindow", "Опишите пробему и постраюсь на формумах найти ответ!"))
        self.problem_input.setPlaceholderText(_translate("MainWindow", "Опишите проблему"))
        self.parse_button.setText(_translate("MainWindow", "Пуск"))
        self.status_label.setText(_translate("MainWindow", "Статус выполнения запроса:"))
        self.show_statistic_button.setText(_translate("MainWindow", "Статистика"))
        self.save_results_button.setText(_translate("MainWindow", "Сохранить результат"))
        self.parser_title.setText(_translate("MainWindow", "Парсер форумов"))
        self.save_result.setText(_translate("MainWindow", "Сохранить результат"))
